// These styles apply to every route in the application
import "../styles/globals.css";
import { Poppins } from "next/font/google";
import { ReactNode } from "react";

export const metadata = {
  title: "Edution",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
